apiVersion: v1
kind: Service

metadata:
  name: status-monitor

spec:
  type: NodePort

  selector:
    app: status-monitor

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32328